-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.



CREATE TABLE LOG (
ID BIGINT() PRIMARY KEY,
IDCHAMADO BIGINT(),
DESCRIÇÃO VARCHAR(255),
DATAATENDIMENTO DATETIME,
DATACONCLUSAO DATETIME,
GRAU INTEGER,
STATUS VARCHAR(12),
ATENDIMENTO Número(4),
FUNCIONARIO VARCHAR(150)/*falha: chave estrangeira*/
)

CREATE TABLE CHAMADO (
ID BIGINT() PRIMARY KEY,
DESCRICAO VARCHAR(255),
DATAABERTURA DATETIME,
DATACONCLUSAO DATETIME,
GRAU INTEGER,
STATUS VARCHAR(12),
IDFUNCIONARIO BIGINT(),
IDATENDIMENTO BIGINT()/*falha: chave estrangeira*//*falha: chave estrangeira*/
)

CREATE TABLE FUNCIONARIO (
ID BIGINT() PRIMARY KEY,
NOME VARCHAR(150),
TELEFONE VARCHAR(15),
EMAIL VARCHAR(150),
CARGO VARCHAR(100)
)

CREATE TABLE ATENDENTE (
ID BIGINT() PRIMARY KEY,
NOME VARCHAR(150),
TELEFONE VARCHAR(15),
EMAIL VARCHAR(150),
USUARIO VARCHAR(80),
SENHA VARCHAR(),
FUNCAO VARCHAR(50),
IDLOGIN BIGINT()/*falha: chave estrangeira*/
)

CREATE TABLE ATENDIMENTO (
ID BIGINT() PRIMARY KEY,
NOME VARCHAR(150),
TELEFONE VARCHAR(15),
EMAIL VARCHAR(150),
USUARIO VARCHAR(80),
IDDESENVOLVEDOR BIGINT(),
IDINFRAESTRUTURA BIGINT(),
IDHELP_DESK BIGINT()/*falha: chave estrangeira*//*falha: chave estrangeira*//*falha: chave estrangeira*/
)

CREATE TABLE LOGIN (
ID BIGINT() PRIMARY KEY,
USUARIO VARCHAR(80),
SENHA VARCHAR()
)

